#!/usr/bin/ruby

require "liquid"
require 'optparse'

book = ARGV[0]
author = ARGV[1]
date= ARGV[2]
front_matter= %(---
layout: post
author: Chris Woodall
title: "#{book} by #{author}"
date: #{date} 15:05
comments: false
categories: reading
image:
---
)

slug = book .downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
File::open("_drafts/reading/#{date}-#{slug}.md", 'w') { |file| file.write(front_matter) }
